import type { Signal, LeaderboardEntry, Battle, Tribe, TierKey } from '@/types'

export const SIGNALS: Signal[] = [
  {
    id: 1,
    coin: 'BTC/USDT',
    direction: 'LONG',
    confidence: 87,
    timeframe: '4H',
    rarity: 'legendary',
    tags: ['SMC', 'Order Block', 'BOS', 'Liquidity'],
    user: 'LegendTrader',
    tier: 'legend',
    accuracy: '89.3%',
    timeAgo: '12m ago',
    entry: '$67,240',
    tp: '$69,800',
    sl: '$66,400',
    likes: 284,
    calledIt: 147,
    description: 'Clean BOS at $67,200 confirmed on 4H. Order Block holding strong with FVG almost fully filled. Expecting continuation to $71k. High probability setup with SMC + Fibonacci confluence at entry zone.',
    images: [],
  },
  {
    id: 2,
    coin: 'ETH/USDT',
    direction: 'SHORT',
    confidence: 73,
    timeframe: '1H',
    rarity: 'epic',
    tags: ['Resistance', 'Bearish Div', 'FVG'],
    user: 'CryptoSniper_X',
    tier: 'sniper',
    accuracy: '78.4%',
    timeAgo: '34m ago',
    entry: '$3,248',
    tp: '$3,050',
    sl: '$3,340',
    likes: 96,
    calledIt: 58,
    description: 'Bearish divergence on RSI with FVG unfilled at $3,380. Rejected previous high cleanly. Tight SL above structure. Precision SMC short play with high R/R.',
    images: [],
  },
  {
    id: 3,
    coin: 'SOL/USDT',
    direction: 'LONG',
    confidence: 91,
    timeframe: '1D',
    rarity: 'mythic',
    tags: ['Breakout', 'Volume', 'Accumulation', 'Whale Inflow'],
    user: 'WhaleMaster',
    tier: 'whale',
    accuracy: '82.1%',
    timeAgo: '1h ago',
    entry: '$176.40',
    tp: '$195.00',
    sl: '$168.50',
    likes: 412,
    calledIt: 239,
    description: 'Perfect storm — SMC confluence, whale accumulation detected on-chain, and Fibonacci 0.618 all aligning. Multi-timeframe confirmation. Strong conviction play.',
    images: [],
  },
]

export const LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, user: 'LegendTrader',   tier: 'legend',     accuracy: '89.3%', calls: 247, streak: 18, pump: '+89,420' },
  { rank: 2, user: 'WhaleMaster',    tier: 'whale',      accuracy: '82.1%', calls: 189, streak: 12, pump: '+64,230' },
  { rank: 3, user: 'CryptoSniper_X', tier: 'sniper',     accuracy: '78.4%', calls: 312, streak: 7,  pump: '+45,110' },
  { rank: 4, user: 'BlockchainBull', tier: 'trader',     accuracy: '74.8%', calls: 98,  streak: 4,  pump: '+28,750' },
  { rank: 5, user: 'DeFiDegen',      tier: 'apprentice', accuracy: '71.2%', calls: 156, streak: 3,  pump: '+19,380' },
  { rank: 6, user: 'AltcoinHunter',  tier: 'sniper',     accuracy: '68.9%', calls: 203, streak: 2,  pump: '+12,640' },
  { rank: 7, user: 'MoonShotMike',   tier: 'trader',     accuracy: '65.4%', calls: 87,  streak: 1,  pump: '+8,920'  },
]

export const BATTLES: Battle[] = [
  {
    id: 1,
    coin: 'BTC/USDT',
    user1: { name: 'LegendTrader',   tier: 'legend', prediction: 'LONG',  target: '$72,000' },
    user2: { name: 'WhaleMaster',    tier: 'whale',  prediction: 'SHORT', target: '$64,000' },
    timeLeft: '2h 34m',
    stake: '50 PUMP',
    watchers: 847,
  },
  {
    id: 2,
    coin: 'ETH/USDT',
    user1: { name: 'CryptoSniper_X', tier: 'sniper', prediction: 'LONG',  target: '$3,500' },
    user2: { name: 'BlockchainBull', tier: 'trader', prediction: 'SHORT', target: '$3,100' },
    timeLeft: '45m',
    stake: '100 PUMP',
    watchers: 1243,
  },
]

export const TRIBES: Tribe[] = [
  {
    name: 'SMC Snipers',
    members: 89,
    accuracy: '78.4%',
    tier: 'sniper',
    description: 'Smart money concepts traders focused on order blocks, BOS, and FVG setups.',
    isPrivate: false,
  },
  {
    name: 'Whale Watch',
    members: 24,
    accuracy: '82.1%',
    tier: 'whale',
    description: 'Tracking on-chain whale wallet movements and institutional flows.',
    isPrivate: true,
  },
  {
    name: 'Degen Arena',
    members: 312,
    accuracy: '61.3%',
    tier: 'apprentice',
    description: 'High risk, high reward plays. Not for the faint of heart. WAGMI.',
    isPrivate: false,
  },
  {
    name: 'Legend Circle',
    members: 12,
    accuracy: '88.7%',
    tier: 'legend',
    description: 'Invite-only elite circle. Consistent top performers only.',
    isPrivate: true,
  },
]

export const FEED_POSTS = [
  {
    id: 1,
    user: 'LegendTrader',
    tier: 'legend' as TierKey,
    accuracy: '89.3%',
    timeAgo: '3m ago',
    type: 'Analysis',
    content: 'BTC looking extremely bullish on the 4H. We got a clean BOS at 67,200, OB holding strong, and FVG almost fully filled. Expecting a push to 71k this week. Stay patient, let price come to you. 🎯',
    coinTags: ['$BTC'],
    likes: 342,
    reposts: 87,
    replies: 43,
    calledIt: 156,
    hasSignal: true,
  },
  {
    id: 2,
    user: 'WhaleMaster',
    tier: 'whale' as TierKey,
    accuracy: '82.1%',
    timeAgo: '12m ago',
    type: 'Signal',
    content: 'ETH shorts incoming. Bearish divergence on RSI, FVG unfilled at 3,380, and we rejected the previous high. Risk managed, tight SL. This is a precision play.',
    coinTags: ['$ETH'],
    likes: 198,
    reposts: 45,
    replies: 28,
    calledIt: 89,
    hasSignal: false,
  },
  {
    id: 3,
    user: 'DegenKing',
    tier: 'apprentice' as TierKey,
    accuracy: '61.2%',
    timeAgo: '24m ago',
    type: 'Degen',
    content: 'Going all in on SOL calls. Nothing to lose everything to gain. LFG 🚀',
    coinTags: ['$SOL'],
    likes: 512,
    reposts: 203,
    replies: 167,
    calledIt: 12,
    hasSignal: false,
  },
  {
    id: 4,
    user: 'CryptoSniper_X',
    tier: 'sniper' as TierKey,
    accuracy: '78.4%',
    timeAgo: '45m ago',
    type: 'News',
    content: 'Fed minutes just dropped. No surprises, rates on hold. This is historically bullish for risk assets in the following 72 hours. BTC, ETH, and SOL setups all align. Thread below 👇',
    coinTags: ['$BTC', '$ETH', '$SOL'],
    likes: 267,
    reposts: 134,
    replies: 56,
    calledIt: 98,
    hasSignal: false,
  },
  {
    id: 5,
    user: 'BlockchainSage',
    tier: 'trader' as TierKey,
    accuracy: '74.2%',
    timeAgo: '1h ago',
    type: 'Analysis',
    content: 'AVAX forming a beautiful accumulation range on the daily. Wyckoff spring happened 3 days ago, now watching for a test of the creek. If it holds, this could be a 40% move.',
    coinTags: ['$AVAX'],
    likes: 143,
    reposts: 67,
    replies: 31,
    calledIt: 54,
    hasSignal: false,
  },
]

export const SIGNAL_REPLIES = [
  { id: 1, user: 'TrendRider99',   tier: 'sniper'  as TierKey, accuracy: '76.8%', timeAgo: '8m ago',  content: 'Clean setup, watching for the retest before entry.' },
  { id: 2, user: 'BlockchainSage', tier: 'trader'  as TierKey, accuracy: '74.2%', timeAgo: '15m ago', content: 'Agree with the BOS confirmation. Volume profile also supports this.' },
  { id: 3, user: 'AltcoinHunter',  tier: 'trader'  as TierKey, accuracy: '71.2%', timeAgo: '22m ago', content: 'Risk seems tight for the reward here, good R/R.' },
]

export const CALLED_IT_USERS = [
  { user: 'WhaleMaster',    tier: 'whale'  as TierKey, accuracy: '82.1%' },
  { user: 'TrendRider99',   tier: 'sniper' as TierKey, accuracy: '76.8%' },
  { user: 'BlockchainSage', tier: 'trader' as TierKey, accuracy: '74.2%' },
]

export const AI_MESSAGES = [
  {
    role: 'assistant' as const,
    content: `Analyzing BTC/USDT on the 4H timeframe...\n\nI've identified a strong SMC setup:\n\n• **Order Block**: $66,800–$67,200 zone acting as support\n• **BOS**: Break of structure confirmed at $67,850\n• **FVG**: Fair value gap between $67,400–$67,600\n\nMy confidence level is 87% LONG. The liquidity sweep at $66,640 has been completed and we're seeing institutional accumulation patterns.`,
  },
  {
    role: 'user' as const,
    content: "What's the key risk to watch?",
  },
  {
    role: 'assistant' as const,
    content: `Key risks to monitor:\n\n• **Stop Hunt Zone**: Bears may push to $66,400 to grab liquidity before the move\n• **Macro Risk**: FOMC meeting in 18 hours could cause volatility\n• **Invalidation**: Close below $66,200 on 4H would invalidate the bullish setup\n\nRecommended: Wait for a retest of the $67,200 OB before entry for a better risk-to-reward ratio.`,
  },
]
